### ISSUE TITLE
Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE and Execute_UpdateSameRecordAtSameTime_ThrowsOccException tests are failing on f45217f

### ISSUE THREAD

**Issue by adrianiftode** [awslabs/amazon-qldb-driver-dotnet#38]
**Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE** 

1)  Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE
      Duration: 438 ms

    2)  Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE (Amazon.QLDBSession.Model.InvalidSessionException: invalid session
   at Moq.SequenceSetup.ExecuteCore(Invocation invocation)
   at Moq.Setup.Execute(Invocation invocation)
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock)
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation)
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.SessionProxy.ExecuteStatement(String txnId, String statement, List`1 parameters)
   at Amazon.QLDB.Driver.Transaction.Execute(String statement, List`1 parameters) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\transaction\Transaction.cs:line 163
   at Amazon.QLDB.Driver.Transaction.Execute(String statement) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\transaction\Transaction.cs:line 139
   at Amazon.QLDB.Driver.TransactionExecutor.Execute(String statement) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\transaction\TransactionExecutor.cs:line 65
   at Amazon.QLDB.Driver.Tests.QldbDriverTests.<>c__DisplayClass16_0.<Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE>b__4(TransactionExecutor txn) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver.Tests\QldbDriverTests.cs:line 357
   at Amazon.QLDB.Driver.QldbSession.Execute[T](Func`2 func) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\session\QldbSession.cs:line 117,False)
      Duration: 377 ms

    3)  Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE (Amazon.QLDB.Driver.QldbTransactionException: QLDB Transaction Exception.
 ---> System.Exception: Exception of type 'System.Exception' was thrown.
   at Amazon.QLDB.Driver.RetryHandler.RetriableExecute[T](Func`1 func, RetryPolicy retryPolicy, Action newSessionAction, Action nextSessionAction, Action`1 retryAction) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\retry\RetryHandler.cs:line 62
   at Amazon.QLDB.Driver.SessionPool.Execute[T](Func`2 func, RetryPolicy retryPolicy, Action`1 retryAction) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\session\SessionPool.cs:line 64
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func, RetryPolicy retryPolicy, Action`1 retryAction) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\driver\QldbDriver.cs:line 223
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func, RetryPolicy retryPolicy) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\driver\QldbDriver.cs:line 197
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\driver\QldbDriver.cs:line 144
   at Amazon.QLDB.Driver.Tests.QldbDriverTests.Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE(Exception exception, Boolean expectThrow) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver.Tests\QldbDriverTests.cs:line 357
   --- End of inner exception stack trace ---
   at Amazon.QLDB.Driver.QldbSession.Execute[T](Func`2 func) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\session\QldbSession.cs:line 147
   at Amazon.QLDB.Driver.SessionPool.<>c__DisplayClass8_0`1.<Execute>b__0() in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\session\SessionPool.cs:line 65
   at Amazon.QLDB.Driver.RetryHandler.RetriableExecute[T](Func`1 func, RetryPolicy retryPolicy, Action newSessionAction, Action nextSessionAction, Action`1 retryAction) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\retry\RetryHandler.cs:line 51,False)
      Duration: 14 ms

      Message: 
        Assert.IsTrue failed. 
      Stack Trace: 
        QldbDriverTests.Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE(Exception exception, Boolean expectThrow) line 361

    4)  Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE (Amazon.QLDB.Driver.QldbDriverException: generic
   at Amazon.QLDB.Driver.RetryHandler.RetriableExecute[T](Func`1 func, RetryPolicy retryPolicy, Action newSessionAction, Action nextSessionAction, Action`1 retryAction) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\retry\RetryHandler.cs:line 62
   at Amazon.QLDB.Driver.SessionPool.Execute[T](Func`2 func, RetryPolicy retryPolicy, Action`1 retryAction) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\session\SessionPool.cs:line 64
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func, RetryPolicy retryPolicy, Action`1 retryAction) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\driver\QldbDriver.cs:line 223
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func, RetryPolicy retryPolicy) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\driver\QldbDriver.cs:line 197
   at Amazon.QLDB.Driver.QldbDriver.Execute[T](Func`2 func) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver\driver\QldbDriver.cs:line 144
   at Amazon.QLDB.Driver.Tests.QldbDriverTests.Execute_ExceptionOnExecute_ShouldOnlyRetryOnISEAndTAOE(Exception exception, Boolean expectThrow) in ..\\amazon-qldb-driver-dotnet\Amazon.QLDB.Driver.Tests\QldbDriverTests.cs:line 357,True)
      Duration: 6 ms

**Execute_UpdateSameRecordAtSameTime_ThrowsOccException**

    Assert.AreEqual failed. Expected:<Amazon.QLDBSession.Model.OccConflictException>. Actual:<Amazon.Runtime.Internal.HttpErrorResponseException>.

**Comment by yoroto** [comment]
@adrianiftode Thank you for reporting it. I've just fixed it. The test case was wrong.

**Comment by adrianiftode** [comment]
@yoroto thank you for addressing the issue. The other test `Execute_UpdateSameRecordAtSameTime_ThrowsOccException` is still failing.

**Comment by allimn** [comment]
Hi @adrianiftode , thanks for reaching out to us. We are working on it and will improve this unstable test.
